# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 116867079bb7d962ecbf5bb0e5ff531eaa131103e58ae627cd64c795527075ebc37da5fd9aab9fb667e30d1a29990e25966800792bf04d109127d008f9434af6
  aws_access_key_id: <%= ENV["AWS_ACCESS_KEY_ID"] %>
  aws_secret_access_key: <%= ENV["AWS_SECRET_ACCESS_KEY"] %>
  devise_secret_key: f3ca2b24527cb8ccb21d542cc7ebb133882af982c5f7dcc01d53c94b2862572d3f7e5fad0a6227146a89e9d691f10ed776d8387093a1c86e96272ab6eb3c8b5a

test:
  secret_key_base: a1292d2fec7d97a6bc9bc6499ba282645e9dbb2fdecb6117bc0c482fbe95198627d9d466ccb50060898981cdbdbd0dfed67a4ddd597a63cbed58f450b45250dd

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  aws_access_key_id: <%= ENV["AWS_ACCESS_KEY_ID"] %>
  aws_secret_access_key: <%= ENV["AWS_SECRET_ACCESS_KEY"] %>
